# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
                     ('register','0002_register'),
                     ('enrollment', '0001_initial'),
                     ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True)),
                ('tipo_servicio', models.ForeignKey(db_column="id_tipo_servicio", to='enrollment.TipoServicio')),
                ('nombre', models.CharField(max_length=100, blank=True, null=True)),
                #('colegio', models.ForeignKey(db_column="id_colegio", to='register.Colegio')),
                #('tipo', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10,null=True)),
                ('usuario_modificacion', models.CharField(max_length=10,null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                #'db_table': 'tipo_servicio',
                'managed': settings.IS_MIGRATE,
                #'managed': False,

            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True)),
                ('colegio', models.ForeignKey(db_column="id_colegio", to='register.Colegio')),
                ('nombre', models.CharField(max_length=100, blank=True, null=True)),
                ('descripcion', models.CharField(max_length=500, blank=True, null=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                #'db_table': 'servicio',
                'managed': settings.IS_MIGRATE,
                #'managed': False,

            },
        ),
        migrations.CreateModel(
            name='AulaCurso',
            fields=[
                ('id_aula_curso', models.AutoField(primary_key=True)),
                ('aula', models.ForeignKey(db_column="id_aula", to='AE_academico.Aula')),
                ('curso', models.ForeignKey(db_column="id_curso", to='AE_academico.Curso')),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                # 'db_table': 'matricula',
                'managed': settings.IS_MIGRATE,
                # 'managed': False,

            },
        ),
        migrations.CreateModel(
            name='CursoDocente',
            fields=[
                ('id_curso_docente', models.AutoField(primary_key=True)),
                ('docente', models.ForeignKey(db_column="id_docente", to='register.Docente')),
                ('curso', models.ForeignKey(db_column="id_aula_curso", to='AE_academico.AulaCurso')),
                ('tutor', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                # 'db_table': 'matricula',
                'managed': settings.IS_MIGRATE,
                # 'managed': False,

            },
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id_horario_aula', models.AutoField(primary_key=True)),
                ('curso', models.ForeignKey(db_column="id_curso", to='AE_academico.Curso')),
                ('docente', models.ForeignKey(db_column="id_docente", to='register.Docente')),
                ('lugar', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                # 'db_table': 'matricula',
                'managed': settings.IS_MIGRATE,
                # 'managed': False,

            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True)),
                ('colegio', models.ForeignKey(db_column="id_colegio", to='register.Colegio')),
                ('encargado', models.ForeignKey(db_column="id_personal", to='register.Personal')),
                ('nombre', models.CharField(max_length=100, blank=True, null=True)),
                ('descripcion', models.CharField(max_length=500, blank=True, null=True)),
                ('fecha_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('comunicado', models.ForeignKey(db_column="id_comunicado", to='APIs.Comunicado', null=True, blank=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                # 'db_table': 'matricula',
                'managed': settings.IS_MIGRATE,
                # 'managed': False,

            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True)),
                ('alumno', models.ForeignKey(db_column='id_alumno', to='register.Alumno')),
                #('curso', models.ForeignKey(db_column='id_curso', to='AE_academico.Curso')),
                ('fecha', models.DateField()),
                ('estado_asistencia', models.IntegerField()),
                ('comentario', models.CharField(max_length=500, blank=True, null=True)),
                ('comunicado', models.ForeignKey(db_column="id_comunicado", to='APIs.Comunicado', null=True, blank=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
            ],
            options={
                # 'db_table': 'matricula',
                'managed': settings.IS_MIGRATE,
                # 'managed': False,

            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id_periodo_academico', models.AutoField(primary_key=True)),
                ('colegio', models.ForeignKey(db_column="id_colegio", to='register.Colegio')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                # 'db_table': 'matricula',
                'managed': settings.IS_MIGRATE,
                # 'managed': False,

            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_nota', models.AutoField(primary_key=True)),
                ('curso', models.ForeignKey(db_column="id_curso", to='AE_academico.Curso')),
                ('colegio', models.ForeignKey(db_column="id_colegio", to='register.Colegio')),
                ('periodo_academico', models.ForeignKey(db_column="id_periodo_academico", to='AE_academico.PeriodoAcademico')),
                ('alumno', models.ForeignKey(db_column='id_alumno', to='register.Alumno')),
                ('nota', models.CharField(max_length=2)),
                ('comunicado', models.ForeignKey(db_column="id_comunicado", to='APIs.Comunicado', null=True, blank=True)),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                # 'db_table': 'matricula',
                'managed': settings.IS_MIGRATE,
                # 'managed': False,

            },
        ),
        migrations.CreateModel(
            name='AulaMatricula',
            fields=[
                ('id_aula_matricula', models.AutoField(primary_key=True)),
                ('aula', models.ForeignKey(db_column="id_aula", to='AE_academico.Aula')),
                ('matricula', models.ForeignKey(db_column="id_matricula", to='enrollment.Matricula')),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                # 'db_table': 'matricula',
                'managed': settings.IS_MIGRATE,
                # 'managed': False,

            },
        ),
        migrations.CreateModel(
            name='RecordatorioAula',
            fields=[
                ('id_recordatorio_aula', models.AutoField(primary_key=True)),
                ('aula', models.ForeignKey(db_column="id_aula", to='AE_academico.Aula')),
                ('nombre', models.CharField(max_length=50, blank=False, null=False)),
                ('descripcion', models.CharField(max_length=200, blank=True, null=True)),
                ('fecha_programacion', models.DateField(blank=False, null=False)),
                ('estado', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('usuario_creacion', models.CharField(max_length=10, null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                # 'db_table': 'matricula',
                'managed': settings.IS_MIGRATE,
                # 'managed': False,
            },
        ),
    ]

