# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('usuario_creacion', models.CharField(max_length=10, verbose_name='Usuario_Creacion', null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, verbose_name='Usuario_Modificacion', null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido_pa', models.CharField(max_length=50)),
                ('apellido_ma', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento', models.CharField(max_length=25)),
                ('numerodocumento', models.CharField(max_length=15)),
                ('sexo', models.CharField(max_length=10)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nac', models.DateField(null=True)),
            ],
            options={
                'db_table': 'persona',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('usuario_creacion', models.CharField(max_length=10, verbose_name='Usuario_Creacion', null=True)),
                ('usuario_modificacion', models.CharField(max_length=10, verbose_name='Usuario_Modificacion', null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('id_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=10)),
                ('id_persona', models.ForeignKey(db_column='id_persona', to='register.Persona', null=True, blank=True))
            ],
            options={
                'db_table': 'telefono',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id_apoderado', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=30)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, to='register.Persona')),
            ],
            options={
                'db_table': 'apoderado',
                #'managed': False,
            },
            bases=('register.persona', models.Model),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('codigoint', models.CharField(blank=True, max_length=15, null=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True,
                                                 to='register.Persona')),
                ('apoderados', models.ManyToManyField(db_table="apoderado_alumno", to='register.Apoderado')),
            ],
            options={
                'db_table': 'alumno',
                #'managed': False,
            },
            bases=('register.persona', models.Model),
        ),
    ]
