# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='Tiposdocumentos',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'tipo_documento',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSexo',
            fields=[
                ('activo', models.BooleanField()),
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tipo_sexo',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposGrados',
            fields=[
                ('activo', models.BooleanField()),
                ('id_tipo_grado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipos_grados',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposMedioPago',
            fields=[
                ('activo', models.BooleanField()),
                ('id_tipo_medio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipos_medio_pago',
                #'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposNivel',
            fields=[
                ('activo', models.BooleanField()),
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipos_nivel',
                #'managed': False,
            },
        ),
    ]
